version: '2.2'

volumes:
  static_value:
  media_value:

services:
  db:
    image: postgres:13-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: kekoslav/yamdb_final
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env